# Generated by Django 5.1 on 2024-08-28 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_customuser_contry_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='contry_code',
            new_name='country_code',
        ),
    ]
