# Generated by Django 5.1 on 2024-08-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_rename_contry_code_customuser_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='other_socials',
        ),
        migrations.AddField(
            model_name='customuser',
            name='linktree_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
