# Generated by Django 5.1 on 2024-09-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
