# Generated by Django 5.1 on 2024-09-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_customuser_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
