# Generated by Django 5.1 on 2024-09-14 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_customuser_credits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='title',
            new_name='user_title',
        ),
    ]
