# Generated by Django 5.1 on 2024-09-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_rename_title_customuser_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='saved_projects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
