# Generated by Django 5.1 on 2024-09-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_alter_project_options_project_applicants_and_more'),
        ('Users', '0015_customuser_saved_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='saved_projects',
        ),
        migrations.AddField(
            model_name='customuser',
            name='saved_projects',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='Projects.project'),
        ),
    ]
