# Generated by Django 5.1 on 2024-09-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_remove_customuser_saved_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sparks',
            field=models.IntegerField(default=0),
        ),
    ]
