# Generated by Django 5.1 on 2024-09-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0019_alter_notification_options_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
