# Generated by Django 5.1 on 2024-09-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0022_remove_transaction_type_transaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('received', 'Received'), ('sent', 'Sent')], max_length=255, null=True),
        ),
    ]
