# Generated by Django 5.1 on 2024-10-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0023_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sparks',
            field=models.IntegerField(default=100),
        ),
    ]
