# Generated by Django 5.1 on 2024-10-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0024_alter_customuser_sparks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('received', 'Received'), ('payment', 'payment')], max_length=255, null=True),
        ),
    ]
