# Generated by Django 5.1 on 2024-10-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0025_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('received', 'Received'), ('payment', 'Payment')], max_length=255, null=True),
        ),
    ]
