# Generated by Django 5.1 on 2024-09-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills_needed',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
