# Generated by Django 5.1 on 2024-09-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_remove_project_updated_at_alter_project_bid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='proposal',
            field=models.TextField(null=True),
        ),
    ]
