# Generated by Django 5.1 on 2024-09-19 00:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_alter_project_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AddField(
            model_name='project',
            name='experience_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('Expert', 'Expert')], max_length=20, null=True),
        ),
    ]
