# Generated by Django 5.1 on 2024-09-22 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0008_project_duration_project_experience_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='duration',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('exchange', 'Exchange'), ('freelancer', 'Freelancer')], default='freelancer', max_length=20),
        ),
    ]
