# Generated by Django 5.1 on 2024-10-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0011_alter_project_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='experience_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20, null=True),
        ),
    ]
