# Generated by Django 5.1 on 2024-10-04 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0012_alter_project_experience_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='applicants',
        ),
    ]
